websocket/src/main/java/fi/iki/elonen/WebSocketFrame.java

If payload string contained a control character (newline) the result binary payload ended with a 0 character. This caused me troubles because I parsed Json payload with chrome browser. Chrome doesn't accept an 0 character at the end in JSON.parse()

Wrong encoding for string with control character

---

core/src/main/java/fi/iki/elonen/NanoHTTPD.java

To avoid exception java.net.BindException: bind failed: EADDRINUSE (Address already in use) at binding to address already in use.

make server socket reuse address

---

core/src/test/java/fi/iki/elonen/HttpKeepAliveTest.java

This fixes the following error message when running the tests:
java.io.FileNotFoundException: /tmp/NanoHTTPD-xxxxxxxxxxxxxxxxxxx (Too many open files)

Ensure that temporary files are closed on HttpKeepAliveTest

---

core/src/main/java/fi/iki/elonen/NanoHTTPD.java

If several files are uploaded using a single input field (multiple), enumerate files and make them all available.
If 3 files are uploaded using:
<input name="upload" type="file" multiple>
They are named by ```session.parseBody(files);```:
upload
upload2
upload3
This way backward compatibilty is preserved.

Support <input type="file" multiple>

---

core/src/main/java/fi/iki/elonen/NanoHTTPD.java

I noticed that I cannot use setStatus to set my own status codes.
This should fix it.

Response.setStatus now accepts arbitrary IStatus-derived instances

---

core/src/main/java/fi/iki/elonen/NanoHTTPD.java

This prevents errors where data.available() provides a different length than indicated in the Content-Length header

Send amount of data set in content-length

---

core/src/main/java/fi/iki/elonen/NanoHTTPD.java

The method delete() of interface TempFile should message a failed delete by throwing an Exception. For the default implementation DefaultTempFile no Exceptions were thrown because the used method delete() of File does not throw an Exception on failure but returns false instead. This problem was fixed by now checking the return value and throwing an Exception if it is false.

Fix no warning in log if temp file was not deleted

---

core/src/main/java/fi/iki/elonen/NanoHTTPD.java
core/src/test/java/fi/iki/elonen/HttpChunkedResponseTest.java
core/src/test/java/fi/iki/elonen/integration/GZipIntegrationTest.java

I tried to keep everything working as it was, but the commit is still a bit bigger than anticipated.
There are a few things around the content length that may be discussed, though. My choices have been as follows:
* The Content-Length header is not sent for gzipped content. While it would be possible, fixed length content would need to be completely read and zipped in order to add that header.
* If the Content-Length header is added manually, the content won't be gzipped. The alternative would be use the value from the header to decide how much data to zip, zip the data and replace the header with the size of the zipped data. (Another alternative would be to just gzip things anyway and leave the header. This would make it easier to simulate broken server implementations.)
Note that even …

Added support for gzip

---

core/src/main/java/fi/iki/elonen/NanoHTTPD.java

A not yet available constructor of GZIPOutputStream was used.

Fix working on Android < 4.4 and Java < 7

---

core/src/main/java/fi/iki/elonen/NanoHTTPD.java
core/src/test/java/fi/iki/elonen/HttpPostRequestTest.java

This removes a spurious `BufferedReader` and should also prevent memory exhaustion DoS by malformed `multipart/form-data` POST.

Improved security and refactor decodeMultipart. Closes #23

---

core/src/main/java/fi/iki/elonen/NanoHTTPD.java

sendContentLengthHeaderIfNotAlreadyPresent() will not be called when encodeAsGzip is true.
In this case, browser will not know where is the end of the response, until connection closed.
For example, in HelloServer, chrome will cost 5 seconds (which is the timeout and connection closed in nanoHttpd) to receive response, while it can be done in 37 ms by chunked transfer.

set transfer encoding to chunked when response is gzip.

---

core/src/main/java/fi/iki/elonen/NanoHTTPD.java

The 408 Request Timeout is the recommended response when performing HTTP Long Polling. https://tools.ietf.org/html/rfc6202#section-5.5
https://tools.ietf.org/html/rfc7231#section-6.5.7 is useful when doing long polling with NanoHTTPD.

Added 408 Request Timeout to Status enum

---

webserver/src/main/java/fi/iki/elonen/SimpleWebServer.java

HLS (http://fr.wikipedia.org/wiki/HTTP_Live_Streaming) can be implemented using SimpleWebServer by hosting m3u8 files and the corresponding mpeg-2 TS fragements. All that is missing are the mime types. The mime type for m3u8 is application/vnd.apple.mpegurl (https://tools.ietf.org/html/draft-pantos-http-live-streaming-04#section-3.1)  and the mime type for .ts is "video/mp2t" (ref: http://tools.ietf.org/html/rfc3555#page-38).
Question: Is it possible to force the m3u8 to be sent as utf-8?

Added Mime type for HLS

---

README.md
webserver/src/main/java/fi/iki/elonen/SimpleWebServer.java
webserver/src/test/java/fi/iki/elonen/AbstractTestHttpServer.java
webserver/src/test/java/fi/iki/elonen/TestCorsHttpServer.java
webserver/src/test/java/fi/iki/elonen/TestCorsHttpServerWithSingleOrigin.java

Find embedded a small contribution to add a basic CORS support to NanoHttpd webserver.
I got inspired from:
* @kasakara answer in the [comment](https://github.com/NanoHttpd/nanohttpd/issues/25#issuecomment-52149315)
* @AdamBien in his [CORS project](https://github.com/AdamBien/cors)

fixes #25 add basic CORS support

---

core/src/main/java/fi/iki/elonen/NanoHTTPD.java

The method getBodySize() returns a long. Parsing the content-length fields as ints limited the possible range (though the cases where this matters should still be rare).
Thanks!

Fix content-length not being parsed as long

---

websocket/src/main/java/fi/iki/elonen/NanoWebSocketServer.java

**Here's the deal:**
- You serve HTTP requests by overriding serve() on NanoHTTPD.
- NanoWebSocketServer (we should call it NanoWSD, as in WebSocket Daemon, btw ... if nothing else, it's consistent with NanoHTTPD) handles upgrade requests by overriding serve(), and if a request isn't a ws upgrade request it returns the default serve() from NanoHTTPD, which defaults to a 404 http response.
**Which leads to the following problem:**
If you want a webserver to handle both HTTP and WS, your only solution would be to override the serve() method in NanoWSD (yes I'm already calling it that, I really like it :p ), because you can no longer reach into NanoHTTPD.serve(), and then copy 90% of the code from NanoWSD.serve() into MyWebServer.serve(), which is really bad and just plain wrong in OOP.
**Of …

Allows WebSocket servers to easily override default HTTP behavior.

---

websocket/src/main/java/fi/iki/elonen/NanoWSD.java
websocket/src/main/java/fi/iki/elonen/NanoWebSocketServer.java
websocket/src/main/java/fi/iki/elonen/samples/echo/DebugWebSocketServer.java
websocket/src/main/java/fi/iki/elonen/samples/echo/EchoSocketSample.java
websocket/src/test/java/fi/iki/elonen/WebSocketResponseHandlerTest.java
websocket/src/test/java/fi/iki/elonen/samples/echo/EchoWebSocketsTest.java

- `NanoWebSocketServer` renamed to `NanoWSD` as discussed.
- Removed event methods from `NanoWSD` and added them under `WebSocket` as abstract methods.
- Moved WebSocket Frame debug methods (on send / receive) from `NanoWSD` into `WebSocket` with name format `debugFrame<Received|Sent>()` as empty methods, so that IDEs don't force users to override them, thus keeping users from being tempted into adding code into them. Also added Javadocs explaining they are debug methods and should not be overriden unless for debug purposes.
- Added `WebSocket.onOpen()` event method that is called right after the `WebSocket` state changes to `State.OPEN`.
- Added `WebSocket.isOpen()` method that checks the internal state.
- Made the `WebSocket` class static and abstract, detaching it from `NanoWSD`.
- …

WebSocket refactoring

---

core/src/main/java/fi/iki/elonen/NanoHTTPD.java
core/src/test/java/fi/iki/elonen/SSLServerSocketFactoryTest.java
core/src/test/java/fi/iki/elonen/ServerSocketFactoryTest.java

I tried to provide my own ServerSocket classes, because I want to use my own Bouncycastle TLS implementation.
Since NanoHTTPD didn't have an option to create other ServerSockets than normal TCP or SSL-Sockets, I added the interface ServerSocketFactory and moved the ServerSocket creation into their own classes.
I also added recognition of (non-standard) \n\n-headers for more tolerance, as well as some public keywords in interfaces.

Added ServerSocketFactory to allow custom ServerSockets;

---

core/src/main/java/fi/iki/elonen/NanoHTTPD.java

The original version will save real IP in headers["remote-addr"] and then write HTTP headers to variable headers. This may cause some security issues. Clients can easily override their real ip by add header 'remote-addr' in http requests.

Decode headers before write remote-addr

---

core/src/main/java/fi/iki/elonen/NanoHTTPD.java
nanolets/src/test/java/fi/iki/elonen/router/AppNanolets.java
webserver/src/main/java/fi/iki/elonen/SimpleWebServer.java
websocket/src/main/java/fi/iki/elonen/samples/echo/EchoSocketSample.java

This pull request is focused on resolving occurrences of Sonar rule squid:S1132 - “Strings literals should be placed on the left side when checking for equality”. You can find more information about the issue here: https://dev.eclipse.org/sonar/rules/show/squid:S1132?layout=true
Please let me know if you have any questions.
Javed.

Code Quality fix - Strings literals should be placed on the left side when checking for equality

---

core/src/main/java/fi/iki/elonen/NanoHTTPD.java
core/src/test/java/fi/iki/elonen/LoadKeyStoreTest.java

When the keystore is loaded from the classpath, if it does not exist the corresponding `InputStream` is null causing the keystore `load` method to initialize an empty one which is not usable for SSL connections.
Suggested fix is to check for this null pointer and then throw a checked exception.

Throw exception if keystore is not found in resources classpath when using SSL

---

core/src/main/java/fi/iki/elonen/NanoHTTPD.java

Using `toString()` in Enum is unsafe as is can be overridden, `name()` is preferred. Moreover, `valueOf()` has the same effect as the lookup in `values()`.
Added a few warning suppression for Eclipse.
Fixed super-minor typo.

Use `Method.valueOf()` instead of looping through `toString()`

---

core/src/main/java/fi/iki/elonen/NanoHTTPD.java

Extra HTTP verbs:
PROPFIND, PROPPATCH, MKCOL, MOVE, COPY, LOCK, UNLOCK
Extra HTTP status code:
207  "Multi-Status"
More detailed BAD REQUEST error message:
When serving a request, if some data is left unconsumed then those data
corrupt the subsequent request. Extended error message makes it easier to identify.

add HTTP verbs and status codes for WebDAV (RFC 4918)

---

nanolets/src/main/java/fi/iki/elonen/router/RouterNanoHTTPD.java
nanolets/src/test/java/fi/iki/elonen/router/TestNanolets.java

When requesting 
`http://localhost:9090/general/param%201/param%202`
a Nanolet configured with a route like 
`/general/:param1/:param2`
won't executed because the empty space (as decoded from %20) is not included in the regular expression to recognize the URL.

Recognize encoded URLs as routable URL.

---

nanolets/src/main/java/fi/iki/elonen/router/RouterNanoHTTPD.java
nanolets/src/test/java/fi/iki/elonen/router/TestNanolets.java

Add ability to be able to set NotFound and NotImplemented handlers since there is currently no ability to overwrite the ones that are set by addMapping().

Add ability to be able to set NotFound and NotImplemented handlers

---

core/src/main/java/fi/iki/elonen/NanoHTTPD.java
core/src/test/java/fi/iki/elonen/StatusTest.java

I've added several missing HTTP Status codes.  I've also added tests that match the enum name against the status code description.  If people add new status codes in the future this forces them to have the enum name match the status code description.  The advantage of this is that its much less likely they will type the same thing wrong twice (See: https://en.wikipedia.org/wiki/Two_pass_verification) and make it less likely that wrong status messages will be sent.

Add several missing HTTP Status codes

---

nanolets/src/main/java/fi/iki/elonen/router/RouterNanoHTTPD.java
nanolets/src/test/java/fi/iki/elonen/router/AppNanolets.java
nanolets/src/test/java/fi/iki/elonen/router/TestNanolets.java

Hi Folks,
If you have the following routes:
/general/:param1
/general/:param1/:param2
and you hit /general/abc/123, you would expect the second route to be executed with param1=abc and param2=123, but what actually happens is that the second route is executed with param1=abc/123.
While this could be fixed by inverting priorities so that things with more parameters will end up first in the list.  This ultimately fails, however, for cases like /user/help vs /user/:param1 where the second would then always execute with param1=help.
My suggestion is to not change priorities at all based on the number of parameters and go entirely based on insertion order.

Fix prioritization of Nanolets to be entirely based on insertion order

---

core/src/main/java/fi/iki/elonen/NanoHTTPD.java

Comments of createClientHandler and createServerRunnable talk about extending ClientHandler and ServerRunnable, but this also needs accessible constructors.

Enable extension of ClientHandler and ServerRunnable

---

core/src/main/java/fi/iki/elonen/NanoHTTPD.java
core/src/test/java/fi/iki/elonen/HttpGetRequestTest.java
core/src/test/java/fi/iki/elonen/HttpHeadRequestTest.java
core/src/test/java/fi/iki/elonen/HttpPostRequestTest.java
core/src/test/java/fi/iki/elonen/HttpServerTest.java
core/src/test/java/fi/iki/elonen/InvalidRequestTest.java

IHTTPSesssion.parms is now a map to a list of values for a given key. The old getParms() interface still exists, but moving forward one should use getParameters()
This tramples on the previous PR by @roloreaper, but I feel this is a cleaner solution (plus it has tests :) ).

Closes #329, #286

---

core/src/main/java/fi/iki/elonen/NanoHTTPD.java

The server was like, if the "content-type" header of response has "text/" in it, then its response will be GZipped. I have added support to GZip the response if it has "/json" as well. When the content type is "application/json", it can be gzipped as it is a textual content anyway. By this, JSONP contents wont be gzipped as it will have content type header as "application/javascript"

If ContentType header has 'json' in it, then the response will be GZIPed

---

core/src/main/java/org/nanohttpd/protocols/http/response/Response.java

If the outputStream is closed by the client, all the loop gets broken pipe exception. Just closing the input stream if exception is caught.

Added exception handling to the sendBody method.  

---

core/src/main/java/org/nanohttpd/protocols/http/HTTPSession.java

This way, clients can use the constant instead of guessing the magic string

Use constant for magic string "postData"

---

README.md

Was getting a ClassNotFoundException for the SimpleWebServer example as shown on the README.

Corrected SimpleWebServer execution path

---

.travis.yml

Oracle JDK 7 is no longer supported on Travis's default build environment, so switch to OpenJDK instead.

Fix travis build setup
